### PR TITLE
Firebase review

### LINKED ISSUE #91: Use firebase/pusher or something to add new annotations to a paper in real time

### PR DESCRIPTION
**Pull request by stuartlynn**
Using firebase for annotations to get syncing goodness. Resolves #91

### CODE REVIEW

**Comment by stuartlynn** [comment]
The failing tests are weird. Having the after_save callback in Annotation is causing the has_many with a foreign key to return an empty array. It only seems to effect the testing environment as it seems to work fine when actually interacting with the site. 

Might be related to this : http://stackoverflow.com/questions/8914121/rspec-testing-has-many-through-and-after-save

Anyone encountered this before?

**Comment by stuartlynn** [comment]
If someone merges this remember to run the rake task to sync firebase with annotations (only needs to be done once)

**Comment by marcrohloff** [comment]
(Not being very familiar with Firebase)
* Can we use the same url for dev and live without a problem
* Can we rely on the data being persistent or can they lose it.

**Comment by stuartlynn** [comment]
1) The keys I am using for the data store are based off of the sha for the papers so as long as that has few collisions on generation I think we can use it for both production and dev just now. We could also either set up another firebase for dev or add a evn based string to the keys for dev and production. 

2) I dont think we can rely on them but we persist the annotations to the database and just push a copy to firebase so we will always have a definitive copy. I might implement a fallback in the front end so that if the firebase call fails we use the standard rails endpoint

**Comment by marcrohloff** [comment]
I don't see any authentication here. What are we doing to prevent people from arbitrarily pushing changes?

**Pull request merged**
