### PR TITLE
Change the issue tag to be able to display markdown

### LINKED ISSUE #151: Markdown not being displayed in collapsed issue

### PR DESCRIPTION
**Pull request by stuartlynn**
fixes #151

### CODE REVIEW

**Comment by arfon** [comment]
@stuartlynn - if this is rebased against master should it be good to deploy?

**Comment by marcrohloff** [comment]
Did you see NY comment as to why I think this is a bad idea?

**Comment by arfon** [comment]
> Did you see NY comment as to why I think this is a bad idea?

No, can you point me to the comment?

**Comment by marcrohloff** [comment]
Weird, but I can''t find it.

Basically the problem is that this allows all markdown to appear in the *collapsed* header. This is problematic for block style markdown (headers, images, lists, code blocks) since they make it hard to tell the height of the collapsed block which in turn makes stacking them impossible. It also makes it impossible to do things like ellipsify the text to one line.

Note that the collapsed issue header does allow span only markdown (bold, italics, inline code, strike out, links) just not the all markdown.

btw, There have been enough changes in the master branch of this code that it would not be worth trying to merge this.

**Comment by arfon** [comment]
Ok thanks for the explanation. 

> btw, There have been enough changes in the master branch of this code that it would not be worth trying to merge this.

:+1:

**Pull request closed without merging**
