### PR TITLE
Made some progress with being able to select text in the pdf. The locati...

### PR DESCRIPTION
**Pull request by stuartlynn**
...on of the divs are off though and I am not sure why. Also its currently very slow. We might need to figure out how to make it much faster

@marcrohloff Not sure how far you got with this but I made some progress. Not worth merging just now till we get the text selection sorted out

### CODE REVIEW

**Comment by marcrohloff** [comment]
I noticed an offset on their example app as well. I would make the text in the text layer some bright color and fiddle with the offsets till they overlay the background text accurately.

**Comment by stuartlynn** [comment]
Yeah that's what I was going to try next. I think that they broke some of the text hi lighting stuff when they upgraded pds.js



—

**Comment by marcrohloff** [comment]
I think we should delete all the old pdf js files to avoid confusion. I would also try and get it loaded through the asset pipeline (should be possible if it is in the vendor directory) in which case we can also skip setting the worker location.

**Comment by marcrohloff** [comment]
I'm waiting for a response here so that I can merge this PR

**Comment by stuartlynn** [comment]
I don't think we should merge until this is fully working. Happy to delete
the old files but as I have said a few times it would be good to have
someone else take a look at trying to get this to work properly. Until the
text actually hi lights in the correct way I don't think that we should
merge this.

**Comment by marcrohloff** [comment]
I was under the impression that it was working and that it couldn't be worse than what I have in the master branch (which just throws errors). I sort of felt that the more often I use it daily the more issues I'll see.
What exactly are the problems with it other than the highlighting being off.

**Comment by stuartlynn** [comment]
It "works" in terms of the code runs and produces text elements. The hi
lighting being off is a pretty big issue, aside from that large text heavy
documents overload the DOM and end up making the entire site sluggish. I
think we should resolve these before merging.

**Comment by marcrohloff** [comment]
OK, But I will probably fix some small things in another branch to get rid
of the errors that are clogging up my log.

**Pull request closed without merging**
