### PR TITLE
Editor controls

### PR DESCRIPTION
**Pull request by stuartlynn**
Controls for editors to be able to assign/remove reviewers and accept / reject a paper.

### CODE REVIEW

**Comment by stuartlynn** [comment]
Resolves #90

**Comment by stuartlynn** [comment]
Resolves #89

**Comment by marcrohloff** [comment]
Doesn't this also cover parts of #13 (which I was in the middle of :( )

**Comment by stuartlynn** [comment]
@marcrohloff I dont think this pertains to #13 that is specifically for rejecting or accepting an individual annotation. This is for the paper as a whole so I think anything you have done on that is fine.

**Comment by stuartlynn** [comment]
I think its ok to get this merged, I will open a ticket for discussion of the icons we want to use, a ticket for @arfon  to generate the rejected end point and an issue to merge the json elements. If you agree @marcrohloff can you go ahead and merge this in?

**Pull request merged**
