### PR TITLE
Archive url magic

### LINKED ISSUE #31: Do something magical when dropping an arXiv ID into the submission form
Currently the submission form looks like this:

screen shot 2015-01-24 at 9 24 44 pm

It's not clear why we need to ask people for the title here - can't we just grab this from the arXiv? Also, it's not clear what happens when you put the URL in - _what_ URL should it be? Ideally all of these should work:

- http://arxiv.org/abs/1407.5117
- http://arxiv.org/pdf/1407.5117.pdf
- 1407.5117

### PR DESCRIPTION
**Pull request by stuartlynn**
Partly resolves #31 Still need to deactivate the button.

### CODE REVIEW

**Comment by stuartlynn** [comment]
@marcrohloff Think this is ready to merge now. Allows a user to submit a paper using either the archive id , the pdf link or the abs link. Other methods can be added by updating the paper-url-resolver 

https://github.com/openjournals/theoj/blob/archive_url_magic/app/assets/components/paper-url-resolver.html

**Comment by stuartlynn** [comment]
Ok I think that should be better now. Fixed the variable name issue and have added some helper text with examples.

**Comment by stuartlynn** [comment]
Ok the regular expressions now have the .pdf as optional

**Comment by marcrohloff** [comment]
Can you rmerge this off master so that it can be merged?

**Pull request merged**
